---
booktitle: Proceedings of The 4th NeurIPS Efficient Natural Language and Speech Processing
  Workshop
shortname: ENLSP-IV 2024
sections:
- name: Training
  title: Training
- name: Model Design \& Architecture
  title: Model Design \& Architecture
- name: Model Efficiency \& Compression
  title: Model Efficiency \& Compression
- name: Inference
  title: Inference
- name: " Benchmark \\& Evaluation"
  title: " Benchmark \\& Evaluation"
- name: 'Applications '
  title: 'Applications '
volume: '262'
year: '2024'
start: &1 2024-12-14
end: 2024-12-14
published: 2024-12-10
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: ENLSP-2024
month: 0
cycles: false
bibtex_editor: Rezagholizadeh, Mehdi and Passban, Peyman and Samiee, Soheila and Partovi
  Nia, Vahid and Cheng, Yu and Deng, Yue and Liu, Qun and Chen, Boxing
editor:
- given: Mehdi
  family: Rezagholizadeh
- given: Peyman
  family: Passban
- given: Soheila
  family: Samiee
- given: Vahid
  family: Partovi Nia
- given: Yu
  family: Cheng
- given: Yue
  family: Deng
- given: Qun
  family: Liu
- given: Boxing
  family: Chen
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 4th NeurIPS Efficient Natural Language and Speech Processing Workshop
    Held in Vancouver, British Columbia, Canada on 14 December 2024

  Published as Volume 262 by the Proceedings of Machine Learning Research on 10 December 2024.

  Volume Edited by:
    Mehdi Rezagholizadeh
    Peyman Passban
    Soheila Samiee
    Vahid Partovi Nia
    Yu Cheng
    Yue Deng
    Qun Liu
    Boxing Chen

  Series Editors:
    Neil D. Lawrence
date_str: 14 Dec
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v262"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v262
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v262
email: ''
conference:
  name: NeurIPS Efficient Natural Language and Speech Processing Workshop
  url: https://neurips2024-enlsp.github.io/
  location: Vancouver, British Columbia, Canada
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v262/enlsp24.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v262/enlsp24.bib
